import type { NextPage } from 'next';
import Head from 'next/head';
import { GiftWomen } from '../components/home/GiftWomen';
import { OurClients } from '../components/home/OurClients';
import { Presentation } from '../components/home/Presentation';
import { Questions } from '../components/home/Questions';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>OepnCard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/logo.png" />
      </Head>
      {/* Pasar todo esto a un componente Home */}
      <Presentation />
      <OurClients />
      <GiftWomen />
      <Questions />
    </>
  );
};

export default Home;