import { CssBaseline, NextUIThemesBreakpoints, ThemeProvider } from '@nextui-org/react';
import type { NextPage } from 'next'
import Image from 'next/image';
import Head from 'next/head';
import React from 'react';
import NavBar from '../components/NavBar';

// Poner en un archivo theme.ts
const breakpoints: NextUIThemesBreakpoints = {
  // Extra small devices (phones)
  xs: { min: '0', max: '650px' },
  // Small devices (tablets)
  sm: { min: '650px', max: '960px' },
  // Medium devices (landscape tablets)
  md: { min: '960px', max: '1280px' },
  // Large devices (desktops)
  lg: { min: '1280px', max: '1400px' },
  // Extra large devices (larger desktops)
  xl: { min: '1400px', max: '1920px' },
};

const Home: NextPage = () => {
  return (
    <ThemeProvider theme={{ breakpoints: breakpoints  }}>
      <CssBaseline />
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <div style={{height: '400px',width:'100vw'}}>
        <Image
          src="/images/icon-logo.png"
          layout='fill'
        />
      </div>
    </ThemeProvider>
  )
}

export default Home;