import type { NextPage } from 'next';
import Head from 'next/head';
import { OurClients } from '../components/home/OurClients';
import { Presentation } from '../components/home/Presentation';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Pasar todo esto a un componente Home */}
      <Presentation />
      <OurClients />
    </>
  );
};

export default Home;